name: Call a reusable workflow

on:
  workflow_dispatch:
    inputs:
      client_repository:
        description: 'repository'
      branch:
        description: 'branch'
      user_id:
        description: 'user_id'
    secrets:
      Token_WF:

jobs:
  Deploy:
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Obtener nombre de organización
        id: org_name
        run: echo "::set-output name=org_name::$(echo ${{ env.GITHUB_REPOSITORY }} | cut -d '/' -f1)"

      - name: Invocar flujo de trabajo de graviton-scan-customer.yaml
        uses: American-Chip/workflow-remote/.github/workflows/graviton-scan-customer.yaml@develop
        with:
          CLIENT_REPOSITORY: ${{ inputs.client_repository }}
          BRANCH: ${{ inputs.branch }}
          USER_id: ${{ inputs.user_id }}
          ORG: ${{ steps.org_name.outputs.org_name }}

    secrets:
      - ac_github_token: ${{ secrets.Token_WF }}

  Deploy_sonar:
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Invocar flujo de trabajo de sonar-reusable.yaml
        uses: American-Chip/workflow-remote/.github/workflows/sonar-reusable.yaml@develop
        with:
          USER_id: ${{ inputs.user_id }}
