name: Call a reusable workflow

on:
  workflow_dispatch:
    inputs:
      client_repository:
        description: 'repository'
      branch:
        description: 'branch'
      user_id:
        description: 'user_id'
    secrets:
      Token_WF:

jobs:

  Deploy:
  
    permissions:
      id-token: write
      contents: read
    uses: American-Chip/workflow-remote/.github/workflows/graviton-scan-customer.yaml@develop
    with:
      CLIENT_REPOSITORY: ${{ inputs.client_repository }}
      BRANCH: ${{ inputs.branch }}
      USER_id: ${{ inputs.user_id }}
      ORG: ${{ join(['ac_customer_', github.repository_owner]) | lower | replace('-', '_') }}
      #ORG: american_chip  # This is the normalized organization name, all lower case and spaces for _ this must be respected.

    secrets:
      ac_github_token: ${{ secrets.Token_WF }}

  Deploy_sonar:
  
    permissions:
      id-token: write
      contents: read
    uses: American-Chip/workflow-remote/.github/workflows/sonar-reusable.yaml@develop
    with:
      USER_id: ${{ inputs.user_id }}  
