name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print Repository Name
        run: | 
          echo "Repository: ${{ env.GITHUB_REPOSITORY }}"
          repository=$(basename $GITHUB_REPOSITORY)
          echo "Repository: $repository"



      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set up SonarQube
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.0.2311-linux.zip
          unzip sonar-scanner-cli-4.6.0.2311-linux.zip
          mv sonar-scanner-4.6.0.2311-linux /opt/sonar-scanner
          echo "export PATH=/opt/sonar-scanner/bin:$PATH" >> $HOME/.bashrc
          source $HOME/.bashrc

      - name: Run SonarQube Analysis
        run: |
          /opt/sonar-scanner/bin/sonar-scanner \
            -Dsonar.projectKey=testlocalP \
            -Dsonar.projectName=testlocal \
            -Dsonar.projectVersion=1.0 \
            -Dsonar.sources=. \
            -Dsonar.language=python \
            -Dsonar.host.url=https://dora.beta.americanchip.io \
            -Dsonar.login=squ_93d1c1e8c504da03350e6f76f9a69ae606ef4c6a \

