name: Call a reusable workflow

on:
  workflow_dispatch:
    inputs:
      user_id:
        description: 'user_id'

jobs:

  Deploy:
  
    permissions:
      id-token: write
      contents: read
    uses: American-Chip/workflow-remote/.github/workflows/sonar-reusable.yaml@develop
    with:
      CLIENT_REPOSITORY: ${{ inputs.client_repository }}      